#!/bin/bash
#code_recorded_by_tech_cochi
clear
sleep 1
echo ""
echo ""
echo " 

███╗░░░███╗░█████╗░██████╗░
████╗░████║██╔══██╗██╔══██╗
██╔████╔██║███████║██║░░██║
██║╚██╔╝██║██╔══██║██║░░██║
██║░╚═╝░██║██║░░██║██████╔╝
╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═════╝░ " | lolcat




echo ""
sleep 1
clear

pkg install php -y
pkg install openssh -y
pkg install unzip -y
pkg install curl -y
sleep 1
clear

echo "Loading==> " | lolcat
sleep 1
clear
echo "Loading====> " | lolcat
sleep 1
clear
echo "Loading=======> " | lolcat
sleep 1
clear
echo " done " | lolcat
sleep 1
clear
unzip techcochi.zip
clear
rm -rf techcochi.zip
clear
bash about.sh
sleep 4
echo ""
echo ""
echo " SUBSCRIBE MY CHANNEL 🔔 " | lolcat
https://youtube.com/channel/UCoY7vE2FkZgnhp7dAtERA2g
echo ""

